### PR TITLE
Revert "added tutorial for numpy-dataset-adaptor"

### PR DESCRIPTION
**Pull request by rlizzo**
Reverts vmtk/vmtk.github.com#4

To fix broken vmtkscripts documentation and tutorial rendering issues

### CODE REVIEW

**Comment by rlizzo** [comment]
@lantiga , it appears I don't have write access to this repo. Please merge this PR to revert to the previous master while I fix the rendering issues in my commit

**Comment by lantiga** [comment]
Hi Rick, sorry for not checking back after merging. I'm merging this one as well as giving you write access. Thank you!

**Comment by rlizzo** [comment]
No worries. Thanks for the quick response.

Is there any way for me to view the rendered vmtk webpage before merging to
master? I Assumed the markdown files would look identical when rendered
(they look fine on my computer) but something clearly messed up when they
are displayed as a webpage.

**Comment by lantiga** [comment]
Do you have Jekyll on your system?
This might be useful: https://help.github.com/articles/troubleshooting-jekyll-builds

**Comment by lantiga** [comment]
I'll take it back, I didn't receive any error messages from the build, so no use. Still, rendering the website with a locally installed Jekyll is the best bet.

**Comment by rlizzo** [comment]
Ok! And no, I don't have Jekyll, but I'll play around with it. I've never had to do any sort of web development outside of setting remote jupyter notebook sessions to act as a frontend for developing on HPC systems.

**Comment by lantiga** [comment]
It should be fairly straightforward to set up (if ruby gems behave :-) ). It just compiles this repository into a static website, so you take a direct look. Let me know if you need help, I'll have some time tomorrow.

**Comment by rlizzo** [comment]
thanks apparently I already had ruby installed on my system, about to install ruby gems. will let you know if i run into any issue.

**Comment by rlizzo** [comment]
wow. ruby gems is a pain in the rear. that took way longer than it should have to get it to find my ruby header files... nothing to update on, just wanted to let you know that your comment on gems was spot on. seems like you've done this before :+1:

**Comment by lantiga** [comment]
Eh eh, yes sir :-)

**Pull request merged**
