### PR TITLE
added tutorial for numpy-dataset-adaptor

### PR DESCRIPTION
**Pull request by rlizzo**
Hey @lantiga, please see attached PR for a tutorial contributed for the numpy-dataset-adaptor (PR https://github.com/vmtk/vmtk/pull/181).

### CODE REVIEW

**Comment by lantiga** [comment]
Fantastic @rlizzo ! Let's merge the adaptor PR today (I'll finish off and merge in a few hours) and the tutorial.
On the other hand I'm still having troubles with the MacOS conda build, but I'll keep at it.

**Comment by rlizzo** [comment]
Let me look over the tutorial one more time before we merge it. Will update
in a bit when Im happy with it - should be done in the next few hours. The
adaptor PR is ready to go, merge at your convenience!

Let me know if there's anything I can do to help with the MacOS conda
build.

-Rick

**Comment by rlizzo** [comment]
@lantiga I just made some final changes and I'm ready to go on the tutorial and the adaptor PR.

**Comment by lantiga** [comment]
Great job! I spotted one typo (recomend -> recommend).

While I was reading, I was wondering why you didn't use `numpy_to_vtk` or `vtk_to_numpy` to convert data arrays back and forth from numpy ndarrays, instead of iterating (for instance in case of images).

**Comment by rlizzo** [comment]
Ahh excellent question. (I love that pyscience blog btw, I'm disappointed it didn't continue for longer). 

To be honest I don't exactly remember why I decided not to use the `vtk.utils.numpy_support` module, but I remember giving it a try and being very frustrated with it. I believe it was something to do with the order of how the arrays needed to be flattened and reshaped. If my memory serves me correctly (and I could be wrong here), i think there was an issue with something breaking when I converted from vtk to numpy, did some operation, converted from numpy to vtk, and then tried to convert back to numpy again. Something got screwed up in the translations, and I wasn't getting the same arrays back out every time. 

After I spent a bunch of time trying to do it that way I just decided to use the new(ish) numpy integration that kitware blogged about https://blog.kitware.com/improved-vtk-numpy-integration/ . It's not the fastest, but it's reliable. 

The only other option is to parallelize the loop, It'd normally have been trivial for me to implement with the multiprocessing library, but I decided not to because: 
1) Having to make it compatible with both python 2 and 3 is a headache and a half. 
2) Having to account for the differences between process forking on Linux and Windows (let alone MacOS... I'm not sure if they stuck with the unix model on this or not). My gut says that having to protect the process within a main body loop would be a pain in the rear to implement. 
3) in certain execution paths which invoke the `pyperun` script, a process que is already generated. In my experience, trying to implement a multiprocess que in a script being called by a higher level process object is just not worth the effort (if it's possible at all).

**Comment by rlizzo** [comment]
Also, just made the typo fix. 

Do you want me to also commit the jupyter (ipython) notebook I used to write all this stuff in? I wasn't sure if you wanted it since everything else was just written in markdown, but not I realize it might be nice to have the original actual .ipynb file if you ever want to edit the contents. let me know and i'll be happy to push it up.

**Comment by lantiga** [comment]
Hey Rick, back to the speed issue, I read the VTK blog and I have another question (sorry, but I really think we should be able to shave that time off with little effort: there's contiguous memory that should be shared or at worst copied in bulk instead of iterated on). Instead of iterating, can't we use something like: 
```
import vtk
from vtk.numpy_interface import dataset_adapter as dsa
a = vtk.vtkFloatArray()
a.SetNumberOfValues(1000000000)
b = dsa.vtkDataArrayToVTKArray(a)
```
At this point `b` is a `VTKArray`, which is a subclass of `numpy.ndarray` (i.e. it's a numpy array for all intents and purposes). For going back:
```
c = dsa.numpyTovtkDataArray(b)
```
For images, you might need to reshape the resulting array and possibly to transpose it to fix ordering of the elements, but that can be done very efficiently by numpy (again without iterating).

**Comment by rlizzo** [comment]
oh my god... moment's like this make me feel like an idiot... VTK arrays use fortran style indexing instead of C. all I needed to do was:

insead of:

```python
for key in pointData

for key in pointDataKeys:
    flatArray = np.array(imageData.PointData.GetArray(key))
    
    it = np.nditer(DataArray['PointData'][key], 
                   flags=['multi_index'], op_flags=['readwrite'])
    for x in it:
        x[...] = flatArray[ImageReader.Image.ComputePointId(it.multi_index)]
```
```
timeit: 1.38 s ± 38.7 ms per loop
```
if I just do:
```python
for key in pointDataKeys:
    flatArray = np.array(imageData.PointData.GetArray(key))
    DataArray['PointData'][key] = flatArray.reshape(DataArray['Dimensions'], order='F')
```
```
timeit: 6.45 ms ± 171 µs per loop
```
and if we check it out:
```python
np.allclose(DataArray['PointData']['ImageScalars'], flatArray.reshape(DataArray['Dimensions'], order='F'))
```
```
True
```
Yeah... that a 300x Speedup for converting VTK to Numpy images.. lol thank you Luca, I just didn't connect the indexing styles to the problem until your comment caused me to think about it again..

Something very similar happens when converting from numpy back to a vtk image, but that was only a sped up by a factor of 15 (lol.)

Wow... this is awesome. Will get those changes pushed as a PR soon!

**Comment by lantiga** [comment]
Ahah :-)
Is there a need for the performance section anymore?

**Comment by rlizzo** [comment]
Just pushed a new commit changing a few things:

1) fixed the tutorial text on the performance section
2) pushed (and merged) a commit to vmtk/vmtk master which updated the pypescript documentation in the added modules to be consistent across scripts. https://github.com/vmtk/vmtk/pull/190
3) updated vmtk/vmtkscripts/contrib/vmtkcontribscripts.py to include the added numpy-support scritps. 
4) ran the vmtkscript2html.sh utility on the most recent build of vmtk/master to autogenerate online documentation for the newly added scripts.

**Comment by rlizzo** [comment]
I also pushed the ipython notebook I used to write the tutorial to a folder in ./tutorials/ipython-notebooks. This could be useful for future editing if you ever needed to change the text and I wasn't around. 

In addition @lantiga @daron1337, 
I noticed a weird discrepancy after running vmtkscripts2html.sh. When I ran `git status` to review the changes, I noticed the module vmtkscripts/vmtkimagelinetracer.py was deleted. I looked in the build bin directory, and sure enough the vmtkimagelinetracer.py script was not there. 

After searching through the vmtk repository I was able to find that as of v1.2, vmtkimagelinetracer.py was included, but it seemed to be deleted as of v1.3. The last commit that dealt with the file is: 

```
commit 59c99778444efd9a08efd7a3e8c50a6a3e951a4e
Merge: 2ce7a6c 831034a
Author: Luca Antiga <luca.antiga@orobix.com>
Date:   Sat Dec 26 21:45:09 2015 +0100

    Merge remote-tracking branch 'origin/master' into vtk6
```

At this point I've used up the totality of my git expertise, and I'm unable to figure out why the script was deleted, and if it was intentional or not. However, I thought it was worth mentioning since the page describing vmtkimagelinetracer was never deleted from the online documentation. Any ideas what happened here?

**Comment by lantiga** [comment]
Hi Rick, the script was deleted because it was very legacy code. We forgot to remove it from the documentation, thanks for pointing this out.

**Comment by lantiga** [comment]
Thank you Rick!

**Comment by rlizzo** [comment]
Thanks Luca, but it appears that something broke in the vmtkscripts documentation page. Also, not all the elements on my tutorial are rendered correctly. I'm reverting the changes and will try to tease out the issue either tonight or tomorrow.

**Pull request merged**
